[package]
name = "spot-timer"
version = "0.1.0"
edition = "2021"

[lib]
name = "spot_timer"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
rust_decimal = "1.36"
itertools = "0.12"
